[env:hglrc_f405]
platform = ststm32
board = genericSTM32F405RG
framework = arduino
upload_protocol = dfu
monitor_speed = 115200

build_flags = 
    -D HSE_VALUE=8000000U
    -D USBCON
    -D USBD_USE_CDC
    -D HAL_PCD_MODULE_ENABLED

lib_deps = 
    Servo
    finani/ICM42688@^1.1.0

lib_ldf_mode = deep+